export const LEVEL_UP_QUOTES: Record<number, string> = {
    1: 'Every story begins with a single play.',
    2: 'You\'ve taken your first step into the experience.',
    3: 'Progress is built one moment at a time.',
    4: 'Momentum has started.',
    5: 'The journey is officially underway.',
    6: 'Curiosity leads the way.',
    7: 'You\'re finding your rhythm.',
    8: 'Consistency creates progress.',
    9: 'The experience deepens.',
    10: 'A strong beginning shapes the story ahead.',
    11: 'Engagement is becoming habit.',
    12: 'The screen remembers your presence.',
    13: 'You\'re not just watching - you\'re progressing.',
    14: 'Patterns turn into commitment.',
    15: 'Momentum is building steadily.',
    16: 'Every session adds weight to your journey.',
    17: 'Growth rarely announces itself - it accumulates.',
    18: 'You\'re moving beyond casual viewing.',
    19: 'The foundation is solidifying.',
    20: 'Progress favors the consistent.',
    21: 'You\'re becoming part of the platform\'s story.',
    22: 'Depth replaces novelty.',
    23: 'Commitment shapes identity.',
    24: 'Your journey is gaining definition.',
    25: 'Experience compounds quietly.',
    26: 'What was new is now familiar territory.',
    27: 'You move with confidence now.',
    28: 'The pace is steady and deliberate.',
    29: 'Presence creates impact.',
    30: 'The journey is no longer accidental.',
    31: 'Momentum has turned into direction.',
    32: 'Your watch history tells a story.',
    33: 'Growth rarely stops for those who continue.',
    34: 'You\'re building something lasting.',
    35: 'Consistency separates the casual from the committed.',
    36: 'The experience now feels intentional.',
    37: 'Your presence carries weight.',
    38: 'Every milestone adds clarity.',
    39: 'Time invested becomes identity.',
    40: 'You\'ve crossed into serious territory.',
    41: 'You are no longer a newcomer.',
    42: 'Your journey has substance now.',
    43: 'Depth over speed - always.',
    44: 'Experience refines taste.',
    45: 'Your story on this platform is unfolding.',
    46: 'Momentum is now undeniable.',
    47: 'The climb feels purposeful.',
    48: 'You\'re shaping your own legacy.',
    49: 'Consistency becomes reputation.',
    50: 'Halfway to legend.',
    51: 'The journey now requires intention.',
    52: 'You\'ve moved beyond habit - this is discipline.',
    53: 'Depth defines your presence.',
    54: 'Your progress stands out.',
    55: 'Commitment creates distinction.',
    56: 'You\'re setting your own pace.',
    57: 'Growth continues where others pause.',
    58: 'The long game suits you.',
    59: 'Strength is built quietly.',
    60: 'Advancement earned, not given.',
    61: 'Your dedication is visible.',
    62: 'You\'re entering rare territory.',
    63: 'Excellence is repetition mastered.',
    64: 'The climb becomes steeper - you continue anyway.',
    65: 'Few reach this point.',
    66: 'Precision replaces impulse.',
    67: 'You move with quiet confidence.',
    68: 'Mastery grows in patience.',
    69: 'Consistency becomes legacy.',
    70: 'You\'re approaching elite ground.',
    71: 'The journey has depth few understand.',
    72: 'Your progression speaks for itself.',
    73: 'Discipline has shaped your path.',
    74: 'You\'ve earned every step.',
    75: 'Commitment is now unmistakable.',
    76: 'You stand apart from the average.',
    77: 'The climb continues upward.',
    78: 'Excellence becomes standard.',
    79: 'Your presence is established.',
    80: 'Elite status is within reach.',
    81: 'Mastery is no accident.',
    82: 'You\'ve invested more than most.',
    83: 'Depth and dedication define you.',
    84: 'The summit is visible.',
    85: 'Few persist this long.',
    86: 'Your journey commands respect.',
    87: 'Progress has become prestige.',
    88: 'Every level now carries weight.',
    89: 'You\'re nearing the pinnacle.',
    90: 'Only the committed reach this height.',
    91: 'The summit is close.',
    92: 'You\'ve outlasted the ordinary.',
    93: 'Discipline has brought you here.',
    94: 'Your journey is exceptional.',
    95: 'Legacy is no longer distant.',
    96: 'The climb defines the climber.',
    97: 'Your progression stands apart.',
    98: 'Almost legendary.',
    99: 'One step from greatness.',
    100: 'Legend is not claimed - it is earned.'
};

export function getLevelQuote(level: number): string {
    const normalizedLevel = Math.max(1, Math.min(100, Math.floor(level)));
    return LEVEL_UP_QUOTES[normalizedLevel] || 'Keep going. Your next chapter is loading.';
}
